version: "3"
services:
  app:
    build:
      context: .
      dockerfile: dev.dockerfile
    image: react-starwars-dev-img
    container_name: react-starwars-dev-app
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src